from __future__ import annotations

from enum import Enum


# Signals are observations only; different extractors may emit them in the future.
class SignalKey(Enum):
    TREND_STARTED = "TREND_STARTED"
    TREND_MATURED = "TREND_MATURED"
    SELLING_PRESSURE_EASED = "SELLING_PRESSURE_EASED"
    STABILIZATION_CONFIRMED = "STABILIZATION_CONFIRMED"
    ENTRY_SETUP_VALID = "ENTRY_SETUP_VALID"
    EDGE_GONE = "EDGE_GONE"
    INVALIDATED = "INVALIDATED"
    DOW_TREND_UP = "DOW_TREND_UP"
    DOW_TREND_DOWN = "DOW_TREND_DOWN"
    DOW_TREND_NEUTRAL = "DOW_TREND_NEUTRAL"
    DOW_TREND_CHANGE_UP_TO_NEUTRAL = "DOW_TREND_CHANGE_UP_TO_NEUTRAL"
    DOW_TREND_CHANGE_DOWN_TO_NEUTRAL = "DOW_TREND_CHANGE_DOWN_TO_NEUTRAL"
    DOW_TREND_CHANGE_NEUTRAL_TO_UP = "DOW_TREND_CHANGE_NEUTRAL_TO_UP"
    DOW_TREND_CHANGE_NEUTRAL_TO_DOWN = "DOW_TREND_CHANGE_NEUTRAL_TO_DOWN"
    DOW_LAST_LOW_L = "DOW_LAST_LOW_L"
    DOW_LAST_LOW_HL = "DOW_LAST_LOW_HL"
    DOW_LAST_LOW_LL = "DOW_LAST_LOW_LL"
    DOW_LAST_HIGH_H = "DOW_LAST_HIGH_H"
    DOW_LAST_HIGH_HH = "DOW_LAST_HIGH_HH"
    DOW_LAST_HIGH_LH = "DOW_LAST_HIGH_LH"
    DOW_NEW_LL = "DOW_NEW_LL"
    DOW_NEW_HH = "DOW_NEW_HH"
    DOW_RESET = "DOW_RESET"
    DOW_BOS_BREAK_DOWN = "DOW_BOS_BREAK_DOWN"
    DOW_BOS_BREAK_UP = "DOW_BOS_BREAK_UP"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    NO_SIGNAL = "NO_SIGNAL"
