CREATE TABLE IF NOT EXISTS rc_episode_exit_features (
  episode_id TEXT PRIMARY KEY,
  ticker TEXT NOT NULL,
  entry_window_date TEXT,
  entry_window_exit_date TEXT,
  as_of_date TEXT NOT NULL,
  computed_at TEXT NOT NULL,
  ew_window_age_days INTEGER,
  ew_window_age_pct_of_10 REAL,
  close_vs_ma10_pct REAL,
  close_vs_ma20_pct REAL,
  close_vs_ma50_pct REAL,
  close_vs_ma100_pct REAL,
  close_vs_ma200_pct REAL,
  ma10_vs_ma20_pct REAL,
  ma20_vs_ma50_pct REAL,
  ma50_vs_ma200_pct REAL,
  ma20_slope_5d REAL,
  ma50_slope_10d REAL,
  pullback_from_20d_high_pct REAL,
  pullback_from_60d_high_pct REAL,
  pullback_from_120d_high_pct REAL,
  bars_since_20d_high INTEGER,
  bars_since_60d_high INTEGER,
  down_leg_depth_pct REAL,
  down_leg_length_bars INTEGER,
  rebound_from_low_pct REAL,
  bars_since_local_low INTEGER,
  ret_1d REAL,
  ret_3d REAL,
  ret_5d REAL,
  ret_10d REAL,
  ret_20d REAL,
  ret_from_low_3d REAL,
  ret_from_low_5d REAL,
  green_days_last_5 INTEGER,
  red_days_last_5 INTEGER,
  green_days_last_10 INTEGER,
  atr5_pct REAL,
  atr14_pct REAL,
  atr20_pct REAL,
  true_range_pct_today REAL,
  range_pct_today REAL,
  range_pct_avg10 REAL,
  volatility_10d REAL,
  volatility_20d REAL,
  volume_vs_avg10 REAL,
  volume_vs_avg20 REAL,
  volume_vs_avg50 REAL,
  down_volume_ratio_5d REAL,
  up_volume_ratio_5d REAL,
  highest_volume_10d_flag INTEGER,
  volume_dryup_pct REAL,
  body_pct_of_range REAL,
  close_location_in_range REAL,
  upper_wick_pct REAL,
  lower_wick_pct REAL,
  inside_day_flag INTEGER,
  outside_day_flag INTEGER,
  gap_up_pct REAL,
  gap_down_pct REAL,
  index_ret_1d REAL,
  index_ret_5d REAL,
  index_ret_20d REAL,
  index_close_vs_ma50_pct REAL,
  index_close_vs_ma200_pct REAL,
  index_volatility_10d REAL,
  distance_from_52w_high_pct REAL
);

CREATE INDEX IF NOT EXISTS idx_rc_episode_exit_features_as_of_date
ON rc_episode_exit_features(as_of_date);

CREATE INDEX IF NOT EXISTS idx_rc_episode_exit_features_ticker_asof
ON rc_episode_exit_features(ticker, as_of_date);
